#!/usr/bin/env python3
"""Generate docs/coverage.md from the live franken_networkx export surface.

The matrix is derived from ``franken_networkx.__all__`` so it reflects the
declared public API instead of a best-effort AST census of ``__init__.py``.

Classification rules:
  RUST_NATIVE   — public callables implemented in ``franken_networkx._fnx``
  PY_WRAPPER    — public Python callables without runtime NetworkX use
  NX_DELEGATED  — public Python callables that import or call NetworkX
  CLASS         — public classes, exceptions, and iterator types
  CONSTANT      — public non-callable values such as ``config`` or ``__version__``
"""

from __future__ import annotations

import argparse
import ast
import difflib
import inspect
import sys
import textwrap
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_PATH = ROOT / "docs/coverage.md"
CATEGORY_ORDER = ("RUST_NATIVE", "PY_WRAPPER", "NX_DELEGATED", "CLASS", "CONSTANT")
NETWORKX_NAMES = {"networkx", "nx", "_nx"}


def load_public_exports():
    sys.path.insert(0, str(ROOT))
    sys.path.insert(0, str(ROOT / "python"))
    import franken_networkx as fnx  # pylint: disable=import-outside-toplevel

    duplicates = []
    seen = set()
    ordered_names = []
    for name in fnx.__all__:
        if name in seen:
            duplicates.append(name)
            continue
        seen.add(name)
        ordered_names.append(name)
    exports = []
    missing = []
    for name in ordered_names:
        try:
            exports.append((name, getattr(fnx, name)))
        except AttributeError:
            missing.append(name)
    if missing:
        joined = ", ".join(sorted(missing))
        raise RuntimeError(f"Names declared in __all__ but missing at runtime: {joined}")
    return exports, sorted(set(duplicates))


def uses_networkx_runtime(obj) -> bool:
    """Return True when the function source imports or references NetworkX."""
    try:
        source = inspect.getsource(obj)
    except (OSError, TypeError):
        return False

    try:
        tree = ast.parse(textwrap.dedent(source))
    except SyntaxError:
        return False

    aliases = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name.split(".")[0] == "networkx":
                    aliases.add(alias.asname or alias.name.split(".")[0])
        elif isinstance(node, ast.ImportFrom):
            if node.module and node.module.split(".")[0] == "networkx":
                aliases.add("networkx")
                for alias in node.names:
                    aliases.add(alias.asname or alias.name)
        elif isinstance(node, ast.Attribute):
            if isinstance(node.value, ast.Name) and node.value.id in (NETWORKX_NAMES | aliases):
                return True
        elif isinstance(node, ast.Name):
            if node.id in aliases:
                return True
    return False


def classify_export(obj) -> str:
    if inspect.isclass(obj):
        return "CLASS"
    if not (inspect.isbuiltin(obj) or inspect.isfunction(obj)):
        return "CONSTANT"

    module_name = getattr(obj, "__module__", "") or ""
    if module_name == "franken_networkx._fnx":
        return "RUST_NATIVE"
    if inspect.isfunction(obj) and uses_networkx_runtime(obj):
        return "NX_DELEGATED"
    return "PY_WRAPPER"


def render_markdown(exports, duplicates) -> str:
    categorized = defaultdict(list)
    module_counts = Counter()

    for name, obj in exports:
        category = classify_export(obj)
        categorized[category].append(name)
        module_name = getattr(obj, "__module__", type(obj).__module__)
        module_counts[module_name] += 1

    total = len(exports)
    lines = [
        "# FrankenNetworkX Coverage Matrix",
        "",
        "*Auto-generated by `scripts/generate_coverage_matrix.py` from `franken_networkx.__all__` — do not edit manually.*",
        "",
        "## Summary",
        "",
        "| Category | Count | % | Rule |",
        "|----------|-------|---|------|",
        f"| RUST_NATIVE | {len(categorized['RUST_NATIVE'])} | {len(categorized['RUST_NATIVE'])*100//max(total,1)}% | native extension exports from `franken_networkx._fnx` |",
        f"| PY_WRAPPER | {len(categorized['PY_WRAPPER'])} | {len(categorized['PY_WRAPPER'])*100//max(total,1)}% | Python-defined exports with no runtime NetworkX dependency detected |",
        f"| NX_DELEGATED | {len(categorized['NX_DELEGATED'])} | {len(categorized['NX_DELEGATED'])*100//max(total,1)}% | Python-defined exports that import or call NetworkX at runtime |",
        f"| CLASS | {len(categorized['CLASS'])} | {len(categorized['CLASS'])*100//max(total,1)}% | public classes, exceptions, iterators |",
        f"| CONSTANT | {len(categorized['CONSTANT'])} | {len(categorized['CONSTANT'])*100//max(total,1)}% | public non-callable values |",
        f"| **Total public exports** | **{total}** | | unique names from `franken_networkx.__all__` |",
        "",
        "All declared public exports are classified. `--check` fails if this generated report drifts from the live module surface.",
        "",
    ]

    if duplicates:
        lines.extend(
            [
                "## Duplicate `__all__` Entries",
                "",
                f"The live module currently declares {len(duplicates)} duplicate name(s) in `__all__`. The matrix deduplicates them before counting the public surface.",
                "",
            ]
        )
        for name in duplicates:
            lines.append(f"- `{name}`")
        lines.append("")

    lines.extend(
        [
        "## Module Breakdown",
        "",
        "| Module | Count |",
        "|--------|-------|",
        ]
    )
    for module_name, count in sorted(module_counts.items(), key=lambda item: (-item[1], item[0])):
        lines.append(f"| `{module_name}` | {count} |")

    for category in CATEGORY_ORDER:
        names = sorted(categorized[category])
        lines.extend(["", f"## {category} exports ({len(names)})", ""])
        for name in names:
            lines.append(f"- `{name}`")

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if docs/coverage.md is stale",
    )
    args = parser.parse_args()

    try:
        exports, duplicates = load_public_exports()
    except Exception as exc:  # pragma: no cover - exercised in CI on failure
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    rendered = render_markdown(exports, duplicates)
    existing = OUT_PATH.read_text(encoding="utf-8") if OUT_PATH.exists() else ""

    if args.check:
        if existing != rendered:
            diff = "".join(
                difflib.unified_diff(
                    existing.splitlines(keepends=True),
                    rendered.splitlines(keepends=True),
                    fromfile=str(OUT_PATH),
                    tofile=f"{OUT_PATH} (regenerated)",
                )
            )
            print(diff or f"{OUT_PATH} is stale", file=sys.stderr)
            return 1
        print(f"{OUT_PATH} is up to date")
        return 0

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(rendered, encoding="utf-8")

    counts = Counter(classify_export(obj) for _, obj in exports)
    print(f"Generated {OUT_PATH} with {len(exports)} unique exports classified")
    if duplicates:
        print(f"  duplicate __all__ entries skipped: {len(duplicates)}")
    for category in CATEGORY_ORDER:
        print(f"  {category}: {counts[category]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
