#!/usr/bin/env python3
"""Generate docs/coverage.md from python/franken_networkx/__init__.py.

Classifies every public export as:
  RUST_NATIVE    — calls _fnx.* directly
  PY_WRAPPER     — pure Python implementation (no NX delegation)
  NX_DELEGATED   — marked with # DELEGATED_TO_NETWORKX
  CLASS          — class definitions (Graph, DiGraph, etc.)
  CONSTANT       — module-level constants

Usage:
    python3 scripts/generate_coverage_matrix.py
"""

import ast
import re
import sys
from pathlib import Path

INIT_PATH = Path("python/franken_networkx/__init__.py")
OUT_PATH = Path("docs/coverage.md")


def classify_function(source_lines, node):
    """Classify a function definition."""
    # Get the source text for this function
    start = node.lineno - 1
    end = node.end_lineno if node.end_lineno else start + 1
    body_text = "\n".join(source_lines[start:end])

    # Check for DELEGATED_TO_NETWORKX marker
    first_line = source_lines[start]
    if "DELEGATED_TO_NETWORKX" in first_line:
        return "NX_DELEGATED"

    # Check for _fnx. calls (Rust native)
    if "_fnx." in body_text:
        return "RUST_NATIVE"

    # Check for import networkx / nx. calls (but not in docstrings)
    # Remove docstrings first
    clean = body_text
    if "import networkx" in clean or "nx." in clean:
        # Could be delegated without the marker — flag as NX_DELEGATED
        if "nx." in clean and "_fnx." not in clean:
            return "NX_DELEGATED"

    return "PY_WRAPPER"


def main():
    if not INIT_PATH.exists():
        print(f"ERROR: {INIT_PATH} not found", file=sys.stderr)
        sys.exit(1)

    source = INIT_PATH.read_text()
    source_lines = source.splitlines()
    tree = ast.parse(source)

    results = {
        "RUST_NATIVE": [],
        "PY_WRAPPER": [],
        "NX_DELEGATED": [],
        "CLASS": [],
    }

    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.FunctionDef):
            if node.name.startswith("_"):
                continue  # skip private
            category = classify_function(source_lines, node)
            results[category].append(node.name)
        elif isinstance(node, ast.ClassDef):
            if not node.name.startswith("_"):
                results["CLASS"].append(node.name)

    # Generate markdown
    total = sum(len(v) for v in results.values())
    rust_count = len(results["RUST_NATIVE"])
    py_count = len(results["PY_WRAPPER"])
    nx_count = len(results["NX_DELEGATED"])
    class_count = len(results["CLASS"])

    lines = [
        "# FrankenNetworkX Coverage Matrix",
        "",
        f"*Auto-generated by `scripts/generate_coverage_matrix.py` — do not edit manually.*",
        "",
        "## Summary",
        "",
        f"| Category | Count | % |",
        f"|----------|-------|---|",
        f"| RUST_NATIVE (calls `_fnx.*` directly) | {rust_count} | {rust_count*100//max(total,1)}% |",
        f"| PY_WRAPPER (pure Python, no NX delegation) | {py_count} | {py_count*100//max(total,1)}% |",
        f"| NX_DELEGATED (delegates to upstream NetworkX) | {nx_count} | {nx_count*100//max(total,1)}% |",
        f"| CLASS (graph types, exceptions, etc.) | {class_count} | {class_count*100//max(total,1)}% |",
        f"| **Total public exports** | **{total}** | |",
        "",
        "## RUST_NATIVE functions",
        "",
    ]
    for name in sorted(results["RUST_NATIVE"]):
        lines.append(f"- `{name}`")

    lines.extend(["", "## PY_WRAPPER functions", ""])
    for name in sorted(results["PY_WRAPPER"]):
        lines.append(f"- `{name}`")

    lines.extend(["", "## NX_DELEGATED functions", ""])
    for name in sorted(results["NX_DELEGATED"]):
        lines.append(f"- `{name}`")

    lines.extend(["", "## CLASS definitions", ""])
    for name in sorted(results["CLASS"]):
        lines.append(f"- `{name}`")

    lines.append("")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines))
    print(f"Generated {OUT_PATH} with {total} exports classified")
    print(f"  RUST_NATIVE: {rust_count}")
    print(f"  PY_WRAPPER:  {py_count}")
    print(f"  NX_DELEGATED: {nx_count}")
    print(f"  CLASS:        {class_count}")


if __name__ == "__main__":
    main()
